syntax on                                                " Enable syntax highlighting.
filetype plugin indent on                                " Enable file type based indentation.

set shell=bash\ -l                                       " Set shell to bash.
set number                                               " Set number lines.
set autoindent                                           " Respect indentation when starting a new line.
set expandtab                                            " Expand tabs to spaces. Essential in Python.
set tabstop=4                                            " Number of spaces tab is counted for.
set shiftwidth=4                                         " Number of spaces to use for auto indent.
set backspace=2                                          " Fix backspace behavior on most terminals.
set spelllang=en_us                                      " Set spell checker.
set nocompatible                                         " Disable compatibility with vi which can cause issues.
set history=100                                          " Set the number of commands to be saved.